/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;

/**
 *
 * @author sammu
 */
public class Adminadministrarbicicleta extends javax.swing.JPanel {

    /**
     * Creates new form adminPenalizar
     */
    public Adminadministrarbicicleta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 360));

        jButton7.setBackground(new java.awt.Color(19, 134, 201));
        jButton7.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton7.setText("Desactivar el uso de una bicicleta");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton8.setBackground(new java.awt.Color(19, 134, 201));
        jButton8.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton8.setText("Activar el uso de una bicicleta");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                                            
      String tiunStr = javax.swing.JOptionPane.showInputDialog(this,
          "Ingrese el TIUN del estudiante para desactivar el uso:");
      if (tiunStr == null || tiunStr.trim().isEmpty()) return;

      try {
          long tiun = Long.parseLong(tiunStr.trim());
          boolean encontrado = false;

          for (com.bicicletas.modelo.Student student : com.bicicletas.modelo.Main.listaEstudiante) {
              if (student.getTiun() == tiun) {
                  student.finalizacionDeUso();
                  /*javax.swing.JOptionPane.showMessageDialog(this,
                      "Uso finalizado con éxito para el estudiante " + student.getUserName(),
                      "Finalización de uso",
                      javax.swing.JOptionPane.INFORMATION_MESSAGE);*/
                  encontrado = true;
                  break;
              }
          }

          if (!encontrado) {
              javax.swing.JOptionPane.showMessageDialog(this,
                  "Ese TIUN no pertenece a ningún estudiante registrado.",
                  "Error",
                  javax.swing.JOptionPane.ERROR_MESSAGE);
          }

      } catch (NumberFormatException e) {
          javax.swing.JOptionPane.showMessageDialog(this, "El TIUN debe ser numérico.");
      }
  

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                                             
        String tiunStr = javax.swing.JOptionPane.showInputDialog(this, 
            "Ingrese el TIUN del estudiante para activar el uso:");
        if (tiunStr == null || tiunStr.trim().isEmpty()) return;

        try {
            long tiun = Long.parseLong(tiunStr.trim());
            boolean encontrado = false;

            for (com.bicicletas.modelo.Student student : com.bicicletas.modelo.Main.listaEstudiante) {
                if (student.getTiun() == tiun) {
                    student.activacionDeUso();
                   /* javax.swing.JOptionPane.showMessageDialog(this,
                        "Uso activado con éxito para el estudiante " + student.getUserName(),
                        "Activación de uso",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);*/
                    encontrado = true;
                    break;
                }
            }

            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Ese TIUN no pertenece a ningún estudiante registrado.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El TIUN debe ser numérico.");
        }


    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
