/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;

/**
 *
 * @author sammu
 */
public class Adminadministrarbicicleta extends javax.swing.JPanel {

    /**
     * Creates new form adminPenalizar
     */
    public Adminadministrarbicicleta() {
        initComponents();
        enterID.setOpaque(false);
    enterID.setBackground(new java.awt.Color(0, 0, 0, 0));
    enterTel.setOpaque(false);
    enterTel.setBackground(new java.awt.Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        user_text2 = new javax.swing.JLabel();
        enterID = new javax.swing.JTextField();
        user_text = new javax.swing.JLabel();
        enterTel = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 360));

        jButton7.setBackground(new java.awt.Color(19, 134, 201));
        jButton7.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton7.setText("Desactivar el uso de una bicicleta");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton8.setBackground(new java.awt.Color(19, 134, 201));
        jButton8.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton8.setText("Activar el uso de una bicicleta");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        user_text2.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text2.setText("Ingrese el ID de la bicicleta");

        enterID.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterID.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterID.setForeground(new java.awt.Color(0,0,0,50));
        enterID.setText("ID de la bicicleta");
        enterID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterIDFocusLost(evt);
            }
        });
        enterID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterIDMousePressed(evt);
            }
        });

        user_text.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text.setText("Ingrese el motivo ");

        enterTel.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterTel.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterTel.setForeground(new java.awt.Color(0,0,0,50));
        enterTel.setText("(opcional)");
        enterTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterTelFocusLost(evt);
            }
        });
        enterTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterTelMousePressed(evt);
            }
        });
        enterTel.addActionListener(this::enterTelActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_text)
                    .addComponent(user_text2)
                    .addComponent(enterID, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterTel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(user_text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String idStr = javax.swing.JOptionPane.showInputDialog(this,
        "Ingrese el ID de la bicicleta a desactivar:");
    if (idStr == null || idStr.trim().isEmpty()) return;

    try {
        int id = Integer.parseInt(idStr.trim());
        boolean encontrada = false;

        for (com.bicicletas.modelo.Station estacion : com.bicicletas.modelo.Main.estaciones) {
            if (estacion.existeBicicleta(id)) {
                estacion.cambiarEstadoBici(id, "mantenimiento");
                com.bicicletas.modelo.Archivo.reescribirArchivo(estacion);
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bicicleta " + id + " en mantenimiento ");
                encontrada = true;
                break;
            }
        }
        if (!encontrada)
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró bicicleta con ID: " + id);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID debe ser numérico.");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String idStr = javax.swing.JOptionPane.showInputDialog(this, 
        "Ingrese el ID de la bicicleta a activar:");
    if (idStr == null || idStr.trim().isEmpty()) return;

    try {
        int id = Integer.parseInt(idStr.trim());
        boolean encontrada = false;

        for (com.bicicletas.modelo.Station estacion : com.bicicletas.modelo.Main.estaciones) {
            if (estacion.existeBicicleta(id)) {
                estacion.cambiarEstadoBici(id, "disponible");
                com.bicicletas.modelo.Archivo.reescribirArchivo(estacion);
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bicicleta " + id + " activada" );
                encontrada = true;
                break;
            }
        }
        if (!encontrada)
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró bicicleta con ID: " + id);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID debe ser numérico.");
    }
    
    
    
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void enterIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterIDFocusLost
        if (enterID.getText().isEmpty()) {
            enterID.setText("TIUN del estudiante");
            enterID.setForeground(new java.awt.Color(0, 0, 0, 50));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_enterIDFocusLost

    private void enterIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterIDMousePressed
        if (enterID.getText().equals("TIUN del estudiante")) {
            enterID.setText("");
            enterID.setForeground(java.awt.Color.BLACK);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_enterIDMousePressed

    private void enterTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterTelFocusLost
        if (enterTel.getText().isEmpty()) {
            enterTel.setText("(opcional)");
            enterTel.setForeground(new java.awt.Color(0, 0, 0, 50));

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTelFocusLost

    private void enterTelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterTelMousePressed
        if (enterTel.getText().equals("(opcional)")) {
            enterTel.setText("");
            enterTel.setForeground(java.awt.Color.BLACK);
        }  // TODO add your handling code here:

    }//GEN-LAST:event_enterTelMousePressed

    private void enterTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterID;
    private javax.swing.JTextField enterTel;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel user_text;
    private javax.swing.JLabel user_text2;
    // End of variables declaration//GEN-END:variables
}
