/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;

/**
 *
 * @author sammu
 */
public class AdminAgregarcicla extends javax.swing.JPanel {

    /**
     * Creates new form adminPenalizar
     */
    public AdminAgregarcicla() {
        initComponents();
        enterID.setOpaque(false);
    enterID.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    jComboBox2.setSelectedIndex(-1);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_text1 = new javax.swing.JLabel();
        user_text2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        user_text3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        enterID = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_text1.setFont(new java.awt.Font("Ancizar Serif", 1, 36)); // NOI18N
        user_text1.setText("AGREGAR CICLA");
        jPanel1.add(user_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 275, 49));

        user_text2.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text2.setText("Ingrese el ID de la bicicleta");
        jPanel1.add(user_text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 91, -1, -1));

        jButton7.setBackground(new java.awt.Color(19, 134, 201));
        jButton7.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton7.setText("Ingresar");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 200, 50));

        user_text3.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text3.setText("Ingrese la estación de la bicicleta");
        jPanel1.add(user_text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calle 53", "CYT", "Uriel", "Calle 45", "Calle 26", "Calle 30" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 420, 30));

        enterID.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterID.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterID.setForeground(new java.awt.Color(0,0,0,50));
        enterID.setText("ID de la bicicleta");
        enterID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterIDFocusLost(evt);
            }
        });
        enterID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterIDMousePressed(evt);
            }
        });
        jPanel1.add(enterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 420, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       long id;
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void enterIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterIDFocusLost
        if (enterID.getText().isEmpty()) {
            enterID.setText("ID de la bicicleta");
            enterID.setForeground(new java.awt.Color(0, 0, 0, 50));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_enterIDFocusLost

    private void enterIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterIDMousePressed
        if (enterID.getText().equals("ID de la bicicleta")) {
            enterID.setText("");
            enterID.setForeground(java.awt.Color.BLACK);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_enterIDMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterID;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel user_text1;
    private javax.swing.JLabel user_text2;
    private javax.swing.JLabel user_text3;
    // End of variables declaration//GEN-END:variables
}
