package com.bicicletas.views;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author VALETOR
 */
public class Bienvenida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bienvenida.class.getName());

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"));

        Image img = icon.getImage();

        Image imgEscalada = img.getScaledInstance(180, 76, Image.SCALE_SMOOTH);

        UNlogo.setIcon(new ImageIcon(imgEscalada));
        setSize(800,600);
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sinCuenta_text = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JButton();
        UNlogo = new javax.swing.JLabel();
        bicirrun_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sinCuenta_text.setFont(new java.awt.Font("Ancizar Sans ExtraLight", 0, 18)); // NOI18N
        sinCuenta_text.setForeground(new java.awt.Color(56, 182, 255));
        sinCuenta_text.setText("¿No tienes cuenta? Regístrate aquí");
        sinCuenta_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sinCuenta_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinCuenta_textMouseClicked(evt);
            }
        });
        getContentPane().add(sinCuenta_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        Bienvenido.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 1, 60)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(19, 134, 201));
        Bienvenido.setText("Bienvenido(a)");
        getContentPane().add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        iniciarSesion.setBackground(new java.awt.Color(56, 182, 255));
        iniciarSesion.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 0, 48)); // NOI18N
        iniciarSesion.setText("Iniciar Sesión");
        iniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarSesion.setMaximumSize(new java.awt.Dimension(276, 65));
        iniciarSesion.setMinimumSize(new java.awt.Dimension(276, 65));
        iniciarSesion.addActionListener(this::iniciarSesionActionPerformed);
        getContentPane().add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N
        getContentPane().add(UNlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bicirrun_text.setFont(new java.awt.Font("Ancizar Sans ExtraLight", 0, 24)); // NOI18N
        bicirrun_text.setText("Bicirrun préstamo de bicicletas");
        getContentPane().add(bicirrun_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void sinCuenta_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinCuenta_textMouseClicked
        Signup registrarse=new Signup();
        registrarse.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_sinCuenta_textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bienvenida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JLabel bicirrun_text;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel sinCuenta_text;
    // End of variables declaration//GEN-END:variables
}
