package com.bicicletas.views;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import com.bicicletas.modelo.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author VALETOR
 */
public class Bienvenida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bienvenida.class.getName());

    /**
     * Creates new form Bienvenida
     */
    int xMouse, yMouse;
    public Bienvenida() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"));

        Image img = icon.getImage();

        Image imgEscalada = img.getScaledInstance(180, 76, Image.SCALE_SMOOTH);

        UNlogo.setIcon(new ImageIcon(imgEscalada));
        setSize(800,600);
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sinCuenta_text = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        UNlogo = new javax.swing.JLabel();
        bicirrun_text = new javax.swing.JLabel();
        iniciarSesion_button = new javax.swing.JPanel();
        IniciarSesion_text = new javax.swing.JLabel();
        panel_superior = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        CERRAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sinCuenta_text.setFont(new java.awt.Font("Ancizar Sans ExtraLight", 0, 18)); // NOI18N
        sinCuenta_text.setForeground(new java.awt.Color(56, 182, 255));
        sinCuenta_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sinCuenta_text.setText("¿No tienes cuenta? Regístrate aquí");
        sinCuenta_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sinCuenta_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinCuenta_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sinCuenta_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sinCuenta_textMouseExited(evt);
            }
        });
        getContentPane().add(sinCuenta_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 310, -1));

        Bienvenido.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 1, 60)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(19, 134, 201));
        Bienvenido.setText("Bienvenido(a)");
        getContentPane().add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N
        getContentPane().add(UNlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        bicirrun_text.setFont(new java.awt.Font("Ancizar Sans ExtraLight", 0, 24)); // NOI18N
        bicirrun_text.setText("Bicirrun préstamo de bicicletas");
        getContentPane().add(bicirrun_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        iniciarSesion_button.setBackground(new java.awt.Color(56, 182, 255));
        iniciarSesion_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iniciarSesion_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarSesion_text.setBackground(new java.awt.Color(56, 182, 255));
        IniciarSesion_text.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 0, 24)); // NOI18N
        IniciarSesion_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesion_text.setText("Iniciar Sesión");
        IniciarSesion_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IniciarSesion_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesion_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesion_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesion_textMouseExited(evt);
            }
        });
        iniciarSesion_button.add(IniciarSesion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        getContentPane().add(iniciarSesion_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 300, 60));

        panel_superior.setBackground(new java.awt.Color(255, 255, 255));
        panel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_superiorMouseDragged(evt);
            }
        });
        panel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_superiorMousePressed(evt);
            }
        });
        getContentPane().add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        CERRAR.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 24)); // NOI18N
        CERRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CERRAR.setText("X");
        CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CERRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CERRAR))
        );

        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinCuenta_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinCuenta_textMouseClicked
        Signup registrarse=new Signup();
        registrarse.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_sinCuenta_textMouseClicked

    private void IniciarSesion_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesion_textMouseClicked

        int x = this.getX();
        int y = this.getY();
        
        
        
        
        
        Login login=new Login();
        login.setLocation(x, y);
        login.setVisible(true);
        
        
        //cerrar el jframe de signup
        
        this.dispose();
        
        
    }//GEN-LAST:event_IniciarSesion_textMouseClicked

    private void panel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panel_superiorMousePressed

    private void panel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel_superiorMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(new Color(19,134,201));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_exitMouseExited

    private void IniciarSesion_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesion_textMouseEntered
        iniciarSesion_button.setBackground(new Color(19,134,201));
        IniciarSesion_text.setForeground(Color.WHITE);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 134, 201), 10, true));
    }//GEN-LAST:event_IniciarSesion_textMouseEntered

    private void IniciarSesion_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesion_textMouseExited
        iniciarSesion_button.setBackground(new Color(56,182,255));
        IniciarSesion_text.setForeground(Color.BLACK);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 182, 255), 10, true));
    }//GEN-LAST:event_IniciarSesion_textMouseExited

    private void sinCuenta_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinCuenta_textMouseEntered
        sinCuenta_text.setForeground(new Color(19,134,201));
    }//GEN-LAST:event_sinCuenta_textMouseEntered

    private void sinCuenta_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinCuenta_textMouseExited
        sinCuenta_text.setForeground(new Color(56,182,255));
    }//GEN-LAST:event_sinCuenta_textMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bienvenida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel CERRAR;
    private javax.swing.JLabel IniciarSesion_text;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JLabel bicirrun_text;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel iniciarSesion_button;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JLabel sinCuenta_text;
    // End of variables declaration//GEN-END:variables
}
