/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;
import com.bicicletas.modelo.Main;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author VALETOR
 */
public class CancelarReserva extends javax.swing.JPanel {

    /**
     * Creates new form CancelarReserva
     */
    public CancelarReserva() {
        initComponents();
        setSize(800,460);
        SetDate();
        seeInfo();
    }
    
    public void seeInfo(){
        /*String id=bici.getId().toString();
        String estRecogida=;
        String estEntrega=;*/
    var reserva = Main.estudianteActual.getReserva();

    if (reserva == null) return;

    cancelarReserva_text2.setText("Bicicleta: " + reserva.getBicicletaReservada().getId());
    cancelarReserva_text3.setText("Estación de recogida: " + reserva.getEstacionRecogida().getName_station());
    cancelarReserva_text.setText("Estación de entrega: " + reserva.getEstacionEntrega().getName_station());
        //Aquí toca poner esos atributos para los textos.
        
    }
    
    public void SetDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
            "Octubre","Noviembre","Diciembre"};
        fecha_text.setText(dia+"/"+meses[month - 1]+"/"+year);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha_panel = new javax.swing.JPanel();
        fecha_text = new javax.swing.JLabel();
        cancel_button = new javax.swing.JPanel();
        cancel_text = new javax.swing.JLabel();
        cancelarReserva_text = new javax.swing.JLabel();
        cancelarReserva_text1 = new javax.swing.JLabel();
        cancelarReserva_text2 = new javax.swing.JLabel();
        cancelarReserva_text3 = new javax.swing.JLabel();
        cancelarReserva_text4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha_panel.setBackground(new java.awt.Color(19, 134, 201));

        fecha_text.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 12)); // NOI18N
        fecha_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_text.setText("{dia}/{month}/{year}");

        javax.swing.GroupLayout fecha_panelLayout = new javax.swing.GroupLayout(fecha_panel);
        fecha_panel.setLayout(fecha_panelLayout);
        fecha_panelLayout.setHorizontalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        fecha_panelLayout.setVerticalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(fecha_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 120, 30));

        cancel_button.setBackground(new java.awt.Color(56, 182, 255));
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel_text.setBackground(new java.awt.Color(56, 182, 255));
        cancel_text.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 0, 24)); // NOI18N
        cancel_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel_text.setText("Cancelar");
        cancel_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_textMouseExited(evt);
            }
        });
        cancel_button.add(cancel_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 300, 60));

        cancelarReserva_text.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 24)); // NOI18N
        cancelarReserva_text.setText("Estación de entrega: {estEntrega}");
        cancelarReserva_text.setToolTipText("");
        add(cancelarReserva_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        cancelarReserva_text1.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 36)); // NOI18N
        cancelarReserva_text1.setText("¿Desea cancelarla?");
        cancelarReserva_text1.setToolTipText("");
        add(cancelarReserva_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        cancelarReserva_text2.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 24)); // NOI18N
        cancelarReserva_text2.setText("Bicicleta: {id}");
        cancelarReserva_text2.setToolTipText("");
        add(cancelarReserva_text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        cancelarReserva_text3.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 24)); // NOI18N
        cancelarReserva_text3.setText("Estación de recogida: {estRecogida}");
        cancelarReserva_text3.setToolTipText("");
        add(cancelarReserva_text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        cancelarReserva_text4.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 36)); // NOI18N
        cancelarReserva_text4.setText("Actualmente tiene una reserva activa");
        cancelarReserva_text4.setToolTipText("");
        add(cancelarReserva_text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_textMouseClicked

    var estudiante = com.bicicletas.modelo.Main.estudianteActual;
    var reserva = estudiante.getReserva();

    if (reserva == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay reserva activa.");
        return;
    }

    // devolver bici a disponible
    reserva.getBicicletaReservada().setState("disponible");

    // limpiar reserva del estudiante
    estudiante.setReserva(null);

    javax.swing.JOptionPane.showMessageDialog(this, "Reserva cancelada.");

    // volver a refrescar menú (opcional pero recomendado)
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    new MenuEstudiante().setVisible(true);

    }//GEN-LAST:event_cancel_textMouseClicked

    private void cancel_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_textMouseEntered
        cancel_button.setBackground(new Color(19,134,201));
        cancel_text.setForeground(Color.WHITE);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 134, 201), 10, true));
    }//GEN-LAST:event_cancel_textMouseEntered

    private void cancel_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_textMouseExited
        cancel_button.setBackground(new Color(56,182,255));
        cancel_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_cancel_textMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel_button;
    private javax.swing.JLabel cancel_text;
    private javax.swing.JLabel cancelarReserva_text;
    private javax.swing.JLabel cancelarReserva_text1;
    private javax.swing.JLabel cancelarReserva_text2;
    private javax.swing.JLabel cancelarReserva_text3;
    private javax.swing.JLabel cancelarReserva_text4;
    private javax.swing.JPanel fecha_panel;
    private javax.swing.JLabel fecha_text;
    // End of variables declaration//GEN-END:variables
}
