/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bicicletas.views;
import com.bicicletas.modelo.*;

import java.awt.Color;
import static java.lang.System.exit;


/**
 *
 * @author sammu
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    int xMouse, yMouse;
    public Login() {
        initComponents();
        
        //para q no coja ni admin ni estudiante
        jComboBox2.setSelectedIndex(-1);
        
        
        
         //valetor esto es para q no se joda , si quieres cambialo pero cuidado con la transparencia
        enterUser.setOpaque(false);
    enterUser.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    enterUser1.setOpaque(false);
    enterUser1.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    enterPswrd.setOpaque(false);
    enterPswrd.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_superior = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        CERRAR = new javax.swing.JLabel();
        enterUser = new javax.swing.JTextField();
        enterUser1 = new javax.swing.JTextField();
        UNlogo = new javax.swing.JLabel();
        enterPswrd = new javax.swing.JPasswordField();
        pswrd_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ancizar Serif Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 134, 201));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR SESIÓN");

        jLabel4.setFont(new java.awt.Font("Ancizar Serif", 0, 24)); // NOI18N
        jLabel4.setText("Seleccione su rol:");

        jComboBox2.setBackground(new java.awt.Color(196, 231, 251));
        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Ancizar Serif Light", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Estudiante" }));
        jComboBox2.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Ancizar Serif", 0, 24)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Ancizar Serif", 0, 24)); // NOI18N
        jLabel3.setText("Identificación:");

        jButton1.setBackground(new java.awt.Color(19, 134, 201));
        jButton1.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        panel_superior.setBackground(new java.awt.Color(255, 255, 255));
        panel_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_superiorMouseDragged(evt);
            }
        });
        panel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_superiorMousePressed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CERRAR.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 24)); // NOI18N
        CERRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CERRAR.setText("X");
        CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CERRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CERRARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CERRARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CERRARMouseExited(evt);
            }
        });
        exit.add(CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        enterUser.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterUser.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterUser.setForeground(new java.awt.Color(0,0,0,50));
        enterUser.setText("Ingrese su identificación");
        enterUser.setOpaque(true);
        enterUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterUserFocusLost(evt);
            }
        });
        enterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterUserMousePressed(evt);
            }
        });
        enterUser.addActionListener(this::enterUserActionPerformed);

        enterUser1.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterUser1.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterUser1.setForeground(new java.awt.Color(0,0,0,50));
        enterUser1.setText("Ingrese un usuario");
        enterUser1.setOpaque(true);
        enterUser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterUser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterUser1FocusLost(evt);
            }
        });
        enterUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterUser1MousePressed(evt);
            }
        });
        enterUser1.addActionListener(this::enterUser1ActionPerformed);

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N

        enterPswrd.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterPswrd.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterPswrd.setForeground(new java.awt.Color(0,0,0,50));
        enterPswrd.setText("********");
        enterPswrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterPswrdFocusLost(evt);
            }
        });
        enterPswrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterPswrdMousePressed(evt);
            }
        });

        pswrd_text.setFont(new java.awt.Font("Ancizar Serif", 0, 24)); // NOI18N
        pswrd_text.setText("Contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UNlogo)
                .addGap(508, 508, 508))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswrd_text)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterUser1)
                            .addComponent(enterUser)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UNlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswrd_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    String rolSeleccionado = jComboBox2.getSelectedItem().toString().trim();
    String nombreIngresado = enterUser1.getText().trim().toLowerCase();
    String idString = enterUser.getText().trim();
    String passwordIngresado = new String(enterPswrd.getPassword()).trim();

    //si no llena todo
    if(nombreIngresado.equals("ingrese un usuario") || idString.equals("ingrese su identificación") || idString.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor llene todos los campos.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    //-------------------------------------------------------------
    int idIngresado = 0;
    try {
        idIngresado = Integer.parseInt(idString);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La identificación debe contener solo números.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean usuarioEncontrado = false;
    
    
    
    //administrador
    if (rolSeleccionado.equals("Administrador")) {
        for (com.bicicletas.modelo.Administrator admin : com.bicicletas.modelo.Main.adminsAutorizados) {
            // Verifica si todo anda bien
           if (admin.getUserName().equals(nombreIngresado) && 
                admin.getCedula() == idIngresado && 
                admin.getContraseña().equals(passwordIngresado)) {
               
                usuarioEncontrado = true;
                javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido Administrador: " + admin.getUserName());
                
                // Redirigir al MenuAdmin
                MenuAdmin menuA = new MenuAdmin();
                menuA.setVisible(true);
                this.dispose(); // Cerrar el login
                break;
            }
        }
    }
    
    //estudiante
    else if (rolSeleccionado.equals("Estudiante")) {
        for (com.bicicletas.modelo.Student student : com.bicicletas.modelo.Main.listaEstudiante) {
            // Verifica nsi todo está bienn
            System.out.println("DB USER: [" + student.getUserName() + "]");
System.out.println("INPUT USER: [" + nombreIngresado + "]");
System.out.println("DB ID: " + student.getCedula());
System.out.println("INPUT ID: " + idIngresado);
System.out.println("DB PASS: [" + student.getContraseña() + "]");
System.out.println("INPUT PASS: [" + passwordIngresado + "]");
System.out.println("-----");

            if (student.getUserName().trim().equalsIgnoreCase(nombreIngresado.trim()) &&
                student.getCedula() == idIngresado &&
                student.getContraseña().trim().equals(passwordIngresado.trim()))
            
            {
                usuarioEncontrado = true;
                Main.estudianteActual = student;
            
                javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido Estudiante: " + student.getUserName());
                MenuEstudiante menuE = new MenuEstudiante();
                menuE.setVisible(true);

                this.dispose(); // Cerrar el login
                break;
                
                }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un rol válido.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Qué pasa si no coincide nada
    if (!usuarioEncontrado) {
    javax.swing.JOptionPane.showMessageDialog(this, "Usuario o identificación incorrectos. Verifique sus datos.", "Acceso Denegado", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void panel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel_superiorMouseDragged

    private void panel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMousePressed
         xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panel_superiorMousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(new Color(19,134,201));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_exitMouseExited

    private void CERRARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseEntered
        exit.setBackground(new Color(19,134,201));        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseEntered

    private void CERRARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseExited
        exit.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseExited

    private void CERRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseClicked
 System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseClicked

    private void enterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterUserActionPerformed

    private void enterUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterUser1ActionPerformed

    private void enterUser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterUser1MousePressed
    if (enterUser1.getText().equals("Ingrese un usuario")) {
        enterUser1.setText(""); // Deja el cuadro en blanco
        enterUser1.setForeground(java.awt.Color.BLACK); // Cambia la letra a negro para lo que vas a escribir
    }
   
    }//GEN-LAST:event_enterUser1MousePressed

    private void enterUser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterUser1FocusLost
    if (enterUser1.getText().isEmpty()) {
        enterUser1.setText("Ingrese un usuario");
        enterUser1.setForeground(new java.awt.Color(0, 0, 0, 50)); // El color gris transparente que tenías
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_enterUser1FocusLost

    private void enterUser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterUser1FocusGained
     
    }//GEN-LAST:event_enterUser1FocusGained

    private void enterUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterUserMousePressed
        if (enterUser.getText().equals("Ingrese su identificación")) {
        enterUser.setText(""); // Deja el cuadro en blanco
        enterUser.setForeground(java.awt.Color.BLACK); // Cambia la letra a negro para lo que vas a escribir
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_enterUserMousePressed

    private void enterUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterUserFocusLost
        if (enterUser.getText().isEmpty()) {
        enterUser.setText("Ingrese su identificación");
        enterUser.setForeground(new java.awt.Color(0, 0, 0, 50)); // El color gris transparente que tenías
    }   // TODO add your handling code here:
    }//GEN-LAST:event_enterUserFocusLost

    private void enterPswrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterPswrdFocusLost
        // TODO add your handling code here:
        if (enterPswrd.getText().isEmpty()) {
            enterPswrd.setText("********");
            enterPswrd.setForeground(new java.awt.Color(0, 0, 0, 50));

        }
    }//GEN-LAST:event_enterPswrdFocusLost

    private void enterPswrdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPswrdMousePressed
        // TODO add your handling code here:
        if (enterPswrd.getText().equals("********")) {
            enterPswrd.setText("");
            enterPswrd.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_enterPswrdMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CERRAR;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JPasswordField enterPswrd;
    private javax.swing.JTextField enterUser;
    private javax.swing.JTextField enterUser1;
    private javax.swing.JPanel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JLabel pswrd_text;
    // End of variables declaration//GEN-END:variables
}
