package com.bicicletas.views;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class MenuEstudiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEstudiante.class.getName());
       
    

     /* Creates new form Login
     */
    private String panelActivo = "inicio";
    int xMouse, yMouse;
    ImageIcon pqrIcon = new ImageIcon(getClass().getResource("/imagenes/pqr.png"));
    Image pqrImg = pqrIcon.getImage();
    Image pqrEscalado = pqrImg.getScaledInstance(60, 45, Image.SCALE_SMOOTH);
    
    ImageIcon pqrNIcon = new ImageIcon(getClass().getResource("/imagenes/pqr_negro.png"));
    Image pqrNImg = pqrNIcon.getImage();
    Image pqrNEscalado = pqrNImg.getScaledInstance(60, 45, Image.SCALE_SMOOTH);
    
    ImageIcon tiempoIcon = new ImageIcon(getClass().getResource("/imagenes/historial.png"));
    Image tiempoImg = tiempoIcon.getImage();
    Image tiempoEscalado = tiempoImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    
    ImageIcon tiempoNIcon = new ImageIcon(getClass().getResource("/imagenes/historial_negro.png"));
    Image tiempoNImg = tiempoNIcon.getImage();
    Image tiempoNEscalado = tiempoNImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    
    ImageIcon reservarIcon = new ImageIcon(getClass().getResource("/imagenes/bicicletas.png"));
    Image reservarImg = reservarIcon.getImage();
    Image reservarEscalado = reservarImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    
    ImageIcon reservarNIcon = new ImageIcon(getClass().getResource("/imagenes/bicicletas_negro.png"));
    Image reservarNImg = reservarNIcon.getImage();
    Image reservarNEscalado = reservarNImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    
    ImageIcon inicioIcon = new ImageIcon(getClass().getResource("/imagenes/inicio.png"));
    Image inicioImg = inicioIcon.getImage();
    Image inicioEscalado = inicioImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    
    ImageIcon inicioNIcon = new ImageIcon(getClass().getResource("/imagenes/inicio_negro.png"));
    Image inicioNImg = inicioNIcon.getImage();
    Image inicioNEscalado = inicioNImg.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        
    public MenuEstudiante() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"));

        Image img = icon.getImage();

        Image imgEscalada = img.getScaledInstance(180, 76, Image.SCALE_SMOOTH);

        UNlogo.setIcon(new ImageIcon(imgEscalada));
        setSize(800,600);
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        //Inicio home=new Inicio();
        BLANK.setLayout(new BorderLayout());
        /*BLANK.removeAll();
        BLANK.add(home, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();*/
        mostrarInicio();
        
        pqr_image.setIcon(new ImageIcon(pqrEscalado));
       
        tiempo_image.setIcon(new ImageIcon(tiempoEscalado));
        
        reservar_image.setIcon(new ImageIcon(reservarEscalado));
        
        //inicio_image.setIcon(new ImageIcon(inicioNEscalado));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio_button = new javax.swing.JPanel();
        inicio_image = new javax.swing.JLabel();
        UNlogo = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        CERRAR = new javax.swing.JLabel();
        panel_superior = new javax.swing.JPanel();
        menuBarra = new javax.swing.JPanel();
        Inicio_text = new javax.swing.JLabel();
        logout_button = new javax.swing.JPanel();
        logout_text = new javax.swing.JLabel();
        Reserva_button = new javax.swing.JPanel();
        reservar_image = new javax.swing.JLabel();
        Tiempo_button = new javax.swing.JPanel();
        tiempo_image = new javax.swing.JLabel();
        pqrs_text1 = new javax.swing.JLabel();
        Tiempo_text1 = new javax.swing.JLabel();
        pqrs_button1 = new javax.swing.JPanel();
        pqr_image = new javax.swing.JLabel();
        Reservar_text1 = new javax.swing.JLabel();
        BLANK = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio_button.setBackground(new java.awt.Color(56, 182, 255));
        Inicio_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        inicio_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicio_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicio_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicio_imageMouseExited(evt);
            }
        });
        /*
        Inicio_button.add(inicio_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));
        */
        Inicio_button.add(inicio_image,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        getContentPane().add(Inicio_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 70));

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N
        getContentPane().add(UNlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 300, 130));

        exit.setBackground(new java.awt.Color(19, 134, 201));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        CERRAR.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 24)); // NOI18N
        CERRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CERRAR.setText("X");
        CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CERRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CERRAR))
        );

        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        panel_superior.setBackground(new java.awt.Color(19, 134, 201));
        panel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_superiorMouseDragged(evt);
            }
        });
        panel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_superiorMousePressed(evt);
            }
        });
        getContentPane().add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        menuBarra.setBackground(new java.awt.Color(19, 134, 201));
        menuBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio_text.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Inicio_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio_text.setText("Inicio");
        menuBarra.add(Inicio_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, -1));

        logout_button.setBackground(new java.awt.Color(56, 182, 255));
        logout_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_text.setFont(new java.awt.Font("Ancizar Sans Medium", 0, 14)); // NOI18N
        logout_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_text.setText("Cerrar Sesión");
        logout_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_textMouseExited(evt);
            }
        });
        logout_button.add(logout_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        menuBarra.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, 30));

        Reserva_button.setBackground(new java.awt.Color(56, 182, 255));
        Reserva_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservar_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservar_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bicicletas.png"))); // NOI18N
        reservar_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservar_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservar_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservar_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservar_imageMouseExited(evt);
            }
        });
        Reserva_button.add(reservar_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        menuBarra.add(Reserva_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, 70));

        Tiempo_button.setBackground(new java.awt.Color(56, 182, 255));
        Tiempo_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiempo_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempo_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial.png"))); // NOI18N
        tiempo_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tiempo_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiempo_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tiempo_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tiempo_imageMouseExited(evt);
            }
        });
        Tiempo_button.add(tiempo_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        menuBarra.add(Tiempo_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 70));

        pqrs_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        pqrs_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pqrs_text1.setText("PQR");
        menuBarra.add(pqrs_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 70, -1));

        Tiempo_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Tiempo_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempo_text1.setText("Tiempo");
        menuBarra.add(Tiempo_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 70, -1));

        pqrs_button1.setBackground(new java.awt.Color(56, 182, 255));
        pqrs_button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pqr_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pqr_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pqr.png"))); // NOI18N
        pqr_image.setToolTipText("");
        pqr_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pqr_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pqr_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pqr_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pqr_imageMouseExited(evt);
            }
        });
        pqrs_button1.add(pqr_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        menuBarra.add(pqrs_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 70, 70));

        Reservar_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Reservar_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reservar_text1.setText("Reservar");
        menuBarra.add(Reservar_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, -1));
        Reservar_text1.getAccessibleContext().setAccessibleParent(Reserva_button);

        getContentPane().add(menuBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 140));

        BLANK.setBackground(new java.awt.Color(255, 255, 255));
        BLANK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(BLANK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel_superiorMouseDragged

    private void panel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panel_superiorMousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.WHITE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new Color(19,134,201));
    }//GEN-LAST:event_exitMouseExited
/*
    private void pqrs_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqrs_buttonMouseEntered
        PQR pqr=new PQR();
        BLANK.removeAll();
        BLANK.add(pqr, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
    }//GEN-LAST:event_pqrs_buttonMouseEntered
*/
    private void logout_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_textMouseClicked
        Bienvenida welcome=new Bienvenida();
        this.dispose();
        welcome.setVisible(true);
        
    }//GEN-LAST:event_logout_textMouseClicked

    private void pqr_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqr_imageMouseEntered
        pqrs_button1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pqr_image.setIcon(new ImageIcon(pqrNEscalado));
    }//GEN-LAST:event_pqr_imageMouseEntered

    private void pqr_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqr_imageMouseExited
        if(!panelActivo.equals("pqr")){
            pqrs_button1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            pqr_image.setIcon(new ImageIcon(pqrEscalado));
    }
    }//GEN-LAST:event_pqr_imageMouseExited

    private void pqr_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqr_imageMouseClicked
        panelActivo = "pqr";
        PQR pqr = new PQR();
        BLANK.removeAll();
        BLANK.add(pqr, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
        actualizarIconos();
    }//GEN-LAST:event_pqr_imageMouseClicked

    private void tiempo_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiempo_imageMouseEntered
        Tiempo_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tiempo_image.setIcon(new ImageIcon(tiempoNEscalado));
    }//GEN-LAST:event_tiempo_imageMouseEntered

    private void tiempo_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiempo_imageMouseExited
        if(!panelActivo.equals("tiempo")){
            Tiempo_button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            tiempo_image.setIcon(new ImageIcon(tiempoEscalado));
    }
    }//GEN-LAST:event_tiempo_imageMouseExited

    private void tiempo_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiempo_imageMouseClicked
        panelActivo="tiempo";
        actualizarIconos();
        Tiempo time =new Tiempo();
        BLANK.removeAll();
        BLANK.add(time, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
    }//GEN-LAST:event_tiempo_imageMouseClicked

    private void inicio_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_imageMouseClicked
        mostrarInicio();
    }//GEN-LAST:event_inicio_imageMouseClicked

    private void reservar_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_imageMouseClicked
        panelActivo="reservar";
        Reservar reservation=new Reservar();
        BLANK.removeAll();
        BLANK.add(reservation, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
        actualizarIconos();
    }//GEN-LAST:event_reservar_imageMouseClicked

    private void inicio_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_imageMouseEntered
        Inicio_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0 , 0, 0), 3));
        inicio_image.setIcon(new ImageIcon(inicioNEscalado));
    }//GEN-LAST:event_inicio_imageMouseEntered

    private void inicio_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_imageMouseExited
        if(!panelActivo.equals("inicio")){
            Inicio_button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            inicio_image.setIcon(new ImageIcon(inicioEscalado));
    }
    }//GEN-LAST:event_inicio_imageMouseExited

    private void reservar_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_imageMouseEntered
        Reserva_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        reservar_image.setIcon(new ImageIcon(reservarNEscalado));
    }//GEN-LAST:event_reservar_imageMouseEntered

    private void reservar_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_imageMouseExited
        if(!panelActivo.equals("reservar")){
            Reserva_button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            reservar_image.setIcon(new ImageIcon(reservarEscalado));
        }
    }//GEN-LAST:event_reservar_imageMouseExited

    private void logout_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_textMouseEntered
        logout_button.setBackground(new Color (19,134,201));
        logout_text.setForeground(Color.WHITE);
        logout_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    }//GEN-LAST:event_logout_textMouseEntered

    private void logout_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_textMouseExited
        logout_button.setBackground(new Color(56,182,255));
        logout_text.setForeground(Color.BLACK);
        logout_button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_logout_textMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuEstudiante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BLANK;
    private javax.swing.JLabel CERRAR;
    private javax.swing.JPanel Inicio_button;
    private javax.swing.JLabel Inicio_text;
    private javax.swing.JPanel Reserva_button;
    private javax.swing.JLabel Reservar_text1;
    private javax.swing.JPanel Tiempo_button;
    private javax.swing.JLabel Tiempo_text1;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel inicio_image;
    private javax.swing.JPanel logout_button;
    private javax.swing.JLabel logout_text;
    private javax.swing.JPanel menuBarra;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JLabel pqr_image;
    private javax.swing.JPanel pqrs_button1;
    private javax.swing.JLabel pqrs_text1;
    private javax.swing.JLabel reservar_image;
    private javax.swing.JLabel tiempo_image;
    // End of variables declaration//GEN-END:variables

    private void mostrarInicio() {
        panelActivo = "inicio";
        Inicio home = new Inicio();
        BLANK.removeAll();
        BLANK.add(home, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
        actualizarIconos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void actualizarIconos(){

        Inicio_button.setBorder(
            panelActivo.equals("inicio")
            ? javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0), 3)
            : javax.swing.BorderFactory.createEmptyBorder()
        );

        Tiempo_button.setBorder(
            panelActivo.equals("tiempo")
            ? javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0), 3)
            : javax.swing.BorderFactory.createEmptyBorder()
        );

        pqrs_button1.setBorder(
            panelActivo.equals("pqr")
            ? javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0), 3)
            : javax.swing.BorderFactory.createEmptyBorder()
        );
        
        Reserva_button.setBorder(
            panelActivo.equals("reservar")
            ? javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0), 3)
            : javax.swing.BorderFactory.createEmptyBorder()
        );
        
        inicio_image.setIcon(new ImageIcon(
            panelActivo.equals("inicio")
            ? inicioNEscalado
            : inicioEscalado));

        tiempo_image.setIcon(new ImageIcon(
            panelActivo.equals("tiempo")
            ? tiempoNEscalado
            : tiempoEscalado));

        pqr_image.setIcon(new ImageIcon(
            panelActivo.equals("pqr")
            ? pqrNEscalado
            : pqrEscalado));
        
        reservar_image.setIcon(new ImageIcon(
            panelActivo.equals("reservar")
            ? reservarNEscalado
            : reservarEscalado));
    }
}

