package com.bicicletas.views;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.ImageIcon;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class MenuEstudiante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEstudiante.class.getName());
       
    

     /* Creates new form Login
     */
    int xMouse, yMouse;
    public MenuEstudiante() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"));

        Image img = icon.getImage();

        Image imgEscalada = img.getScaledInstance(180, 76, Image.SCALE_SMOOTH);

        UNlogo.setIcon(new ImageIcon(imgEscalada));
        setSize(800,600);
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        Inicio home=new Inicio();
        BLANK.setLayout(new BorderLayout());
        BLANK.removeAll();
        BLANK.add(home, BorderLayout.CENTER);
        BLANK.revalidate();
        BLANK.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UNlogo = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        CERRAR = new javax.swing.JLabel();
        panel_superior = new javax.swing.JPanel();
        menuBarra = new javax.swing.JPanel();
        Inicio_text = new javax.swing.JLabel();
        logout_button = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Inicio_button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Reserva_button = new javax.swing.JPanel();
        Tiempo_button = new javax.swing.JPanel();
        pqrs_text1 = new javax.swing.JLabel();
        Tiempo_text1 = new javax.swing.JLabel();
        pqrs_button1 = new javax.swing.JPanel();
        Reservar_text1 = new javax.swing.JLabel();
        BLANK = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N
        getContentPane().add(UNlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 300, 130));

        exit.setBackground(new java.awt.Color(19, 134, 201));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        CERRAR.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 24)); // NOI18N
        CERRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CERRAR.setText("X");
        CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CERRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CERRAR))
        );

        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        panel_superior.setBackground(new java.awt.Color(19, 134, 201));
        panel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_superiorMouseDragged(evt);
            }
        });
        panel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_superiorMousePressed(evt);
            }
        });
        getContentPane().add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        menuBarra.setBackground(new java.awt.Color(19, 134, 201));
        menuBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio_text.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Inicio_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio_text.setText("Inicio");
        menuBarra.add(Inicio_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, -1));

        logout_button.setBackground(new java.awt.Color(56, 182, 255));
        logout_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ancizar Sans Medium", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cerrar Sesión");
        logout_button.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        menuBarra.add(logout_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, 30));

        Inicio_button.setBackground(new java.awt.Color(56, 182, 255));
        Inicio_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        Inicio_button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        menuBarra.add(Inicio_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 70));

        Reserva_button.setBackground(new java.awt.Color(56, 182, 255));
        Reserva_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuBarra.add(Reserva_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, 70));

        Tiempo_button.setBackground(new java.awt.Color(56, 182, 255));
        Tiempo_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuBarra.add(Tiempo_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 70));

        pqrs_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        pqrs_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pqrs_text1.setText("PQRS");
        menuBarra.add(pqrs_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 70, -1));

        Tiempo_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Tiempo_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempo_text1.setText("Tiempo");
        menuBarra.add(Tiempo_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 70, -1));

        pqrs_button1.setBackground(new java.awt.Color(56, 182, 255));
        pqrs_button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuBarra.add(pqrs_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 70, 70));

        Reservar_text1.setFont(new java.awt.Font("Ancizar Sans SemiBold", 0, 18)); // NOI18N
        Reservar_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reservar_text1.setText("Reservar");
        menuBarra.add(Reservar_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, -1));

        getContentPane().add(menuBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 140));

        BLANK.setBackground(new java.awt.Color(255, 255, 255));
        BLANK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(BLANK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel_superiorMouseDragged

    private void panel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panel_superiorMousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.WHITE);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new Color(19,134,201));
    }//GEN-LAST:event_exitMouseExited
/*
    private void pqrs_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqrs_buttonMouseEntered
        ADD YOUR CODE HERE
    }//GEN-LAST:event_pqrs_buttonMouseEntered
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuEstudiante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BLANK;
    private javax.swing.JLabel CERRAR;
    private javax.swing.JPanel Inicio_button;
    private javax.swing.JLabel Inicio_text;
    private javax.swing.JPanel Reserva_button;
    private javax.swing.JLabel Reservar_text1;
    private javax.swing.JPanel Tiempo_button;
    private javax.swing.JLabel Tiempo_text1;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel logout_button;
    private javax.swing.JPanel menuBarra;
    private javax.swing.JPanel panel_superior;
    private javax.swing.JPanel pqrs_button1;
    private javax.swing.JLabel pqrs_text1;
    // End of variables declaration//GEN-END:variables
}
