package com.bicicletas.views;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.ImageIcon;

import java.util.ArrayList;

import com.bicicletas.modelo.*;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sammu
 */
 /*
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form Login

     
    int xMouse, yMouse;
    public MenuAdmin() {
        initComponents();
        SetDate();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"));

        Image img = icon.getImage();

        Image imgEscalada = img.getScaledInstance(200, 50, Image.SCALE_SMOOTH);

        UNlogo.setIcon(new ImageIcon(imgEscalada));
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
    
    }
    
   

    */


public class MenuAdmin extends javax.swing.JFrame {
    
    public MenuAdmin() {
    this.listaEstudiante = new java.util.ArrayList<>();
    this.estaciones = new java.util.ArrayList<>();
    this.listaComentarios = new java.util.ArrayList<>();
    this.administrador = null;
    
    initComponents();
    SetDate();
    configurarImagenes();
    
   
}
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    
     private ArrayList<Student> listaEstudiante;
    private ArrayList<Station> estaciones;
    private ArrayList<Comment> listaComentarios;
    private Administrator administrador;

    int xMouse, yMouse; 

   
   
   public MenuAdmin(ArrayList<Student> listaEstudiante, ArrayList<Station> estaciones, ArrayList<Comment> listaComentarios, Administrator administrador) {
       
    this.listaEstudiante = listaEstudiante;
    this.estaciones = estaciones;
    this.listaComentarios = listaComentarios;
    this.administrador = administrador;
       
        initComponents();
        SetDate();
    
    
        
    
    
        if (estaciones.isEmpty()) {
            estaciones.add(new Station("Calle 53", 2));
            estaciones.add(new Station("CYT", 2));
            estaciones.add(new Station("Uriel", 15));   
            estaciones.add(new Station("Calle 45", 15));
        }
        
       
        
      
    }
    
    
        private void SetDate() {
    LocalDate now = LocalDate.now();
    int year = now.getYear();
    int dia = now.getDayOfMonth();
    int month = now.getMonthValue();
    String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
        "Octubre","Noviembre","Diciembre"};
    jLabel2.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
}
        private void configurarImagenes() {
            
            if (Penalizar_button.getIcon() != null) {
            
            Image img = ((javax.swing.ImageIcon) Penalizar_button.getIcon()).getImage();
            Image imgEscalada = img.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
            Penalizar_button.setIcon(new javax.swing.ImageIcon(imgEscalada));
            
        }   
        }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AgregarCicla_button = new javax.swing.JButton();
        Penalizar_button = new javax.swing.JButton();
        Reglas_button = new javax.swing.JButton();
        Reportes_button = new javax.swing.JButton();
        QuitarEstudiante_button = new javax.swing.JButton();
        CerrarSesion_button = new javax.swing.JButton();
        AdminCiclas_button = new javax.swing.JButton();
        panel_superior = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        CERRAR = new javax.swing.JLabel();
        UNlogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 134, 201));
        jPanel2.setPreferredSize(new java.awt.Dimension(873, 190));

        AgregarCicla_button.setBackground(new java.awt.Color(56, 182, 255));
        AgregarCicla_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar_bicicleta.png"))); // NOI18N
        AgregarCicla_button.setText("agregar cicla");
        AgregarCicla_button.addActionListener(this::AgregarCicla_buttonActionPerformed);

        Penalizar_button.setBackground(new java.awt.Color(56, 182, 255));
        Penalizar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/penalizar_estudiante.png"))); // NOI18N
        Penalizar_button.setText("penalizar");
        Penalizar_button.addActionListener(this::Penalizar_buttonActionPerformed);

        Reglas_button.setBackground(new java.awt.Color(56, 182, 255));
        Reglas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reglas.png"))); // NOI18N
        Reglas_button.setText("Reglas");
        Reglas_button.addActionListener(this::Reglas_buttonActionPerformed);

        Reportes_button.setBackground(new java.awt.Color(56, 182, 255));
        Reportes_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes_de_estudiantes.png"))); // NOI18N
        Reportes_button.setText("reportes");
        Reportes_button.addActionListener(this::Reportes_buttonActionPerformed);

        QuitarEstudiante_button.setBackground(new java.awt.Color(56, 182, 255));
        QuitarEstudiante_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar_acceso_estudiante.png"))); // NOI18N
        QuitarEstudiante_button.setText("quitar acceso");
        QuitarEstudiante_button.addActionListener(this::QuitarEstudiante_buttonActionPerformed);

        CerrarSesion_button.setBackground(new java.awt.Color(56, 182, 255));
        CerrarSesion_button.setText("Cerrar sesión");

        AdminCiclas_button.setBackground(new java.awt.Color(56, 182, 255));
        AdminCiclas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrar_bicicleta.png"))); // NOI18N
        AdminCiclas_button.setText("Admin ciclas");
        AdminCiclas_button.addActionListener(this::AdminCiclas_buttonActionPerformed);

        panel_superior.setBackground(new java.awt.Color(19, 134, 201));
        panel_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_superiorMouseDragged(evt);
            }
        });
        panel_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_superiorMousePressed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(19, 134, 201));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.setLayout(new java.awt.BorderLayout());

        CERRAR.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 24)); // NOI18N
        CERRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CERRAR.setText("X");
        CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CERRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CERRARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CERRARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CERRARMouseExited(evt);
            }
        });
        exit.add(CERRAR, java.awt.BorderLayout.CENTER);

        UNlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/universidad-nacional-de-colombia-sede-bogota-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UNlogo)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Penalizar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarCicla_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Reglas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reportes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QuitarEstudiante_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminCiclas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(CerrarSesion_button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AdminCiclas_button, AgregarCicla_button, Penalizar_button, QuitarEstudiante_button, Reglas_button, Reportes_button});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UNlogo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Penalizar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(QuitarEstudiante_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reglas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgregarCicla_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(8, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminCiclas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Reportes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CerrarSesion_button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AdminCiclas_button, AgregarCicla_button, Penalizar_button, QuitarEstudiante_button, Reglas_button, Reportes_button});

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 830, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 820, 360));

        jPanel3.setBackground(new java.awt.Color(56, 182, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(56, 182, 255));
        jLabel1.setFont(new java.awt.Font("Ancizar Serif ExtraBold", 0, 12)); // NOI18N
        jLabel1.setText("Administración / Página principal");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 270, 14));

        jLabel2.setFont(new java.awt.Font("Ancizar Serif Light", 0, 18)); // NOI18N
        jLabel2.setText("Hoy es {dia} de {month} del {year}");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 185, 820, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 815, 592);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited

        exit.setBackground(new Color(19,134,201));
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void CERRARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseExited
        exit.setBackground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseExited

    private void CERRARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseEntered
        exit.setBackground(new Color(19,134,201));        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseEntered

    private void CERRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CERRARMouseClicked

    private void panel_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_panel_superiorMousePressed

    private void panel_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_superiorMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_panel_superiorMouseDragged

    private void AdminCiclas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCiclas_buttonActionPerformed
        Adminadministrarbicicleta vistaAdminBici = new Adminadministrarbicicleta();

        // 2. Le asignamos el tamaño exacto del contenedor principal (jPanel4)
        vistaAdminBici.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaAdminBici.setLocation(0, 0);

        // 3. Limpiamos el panel contenedor e insertamos la nueva vista
        jPanel4.removeAll();
        jPanel4.add(vistaAdminBici, java.awt.BorderLayout.CENTER);

        // 4. Forzamos a Java a redibujar los componentes en pantalla
        jPanel4.revalidate();
        jPanel4.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_AdminCiclas_buttonActionPerformed

    private void QuitarEstudiante_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarEstudiante_buttonActionPerformed
        // 1. Creamos la instancia del panel para eliminar estudiantes
        AdminQuitarEstudiante vistaQuitarEstudiante = new AdminQuitarEstudiante();

        // 2. Le asignamos el tamaño exacto del contenedor principal (jPanel4)
        vistaQuitarEstudiante.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaQuitarEstudiante.setLocation(0, 0);

        // 3. Limpiamos el panel contenedor e insertamos la nueva vista
        jPanel4.removeAll();
        jPanel4.add(vistaQuitarEstudiante, java.awt.BorderLayout.CENTER);

        // 4. Forzamos a Java a redibujar los componentes en pantalla
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_QuitarEstudiante_buttonActionPerformed

    private void Reportes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reportes_buttonActionPerformed

        AdminReportes vistaReportes = new AdminReportes();

        // 2. Le asignamos el tamaño exacto del contenedor blanco (jPanel4)
        vistaReportes.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaReportes.setLocation(0, 0);

        // 3. Vaciamos el contenedor y metemos el nuevo panel de reportes
        jPanel4.removeAll();
        jPanel4.add(vistaReportes, java.awt.BorderLayout.CENTER);

        // 4. Refrescamos la interfaz gráfica para pintar los nuevos componentes
        jPanel4.revalidate();
        jPanel4.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_Reportes_buttonActionPerformed

    private void Reglas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reglas_buttonActionPerformed
        Reglas vistaReglas = new Reglas();

        // 2. Le asignamos el tamaño exacto del contenedor (jPanel4)
        vistaReglas.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaReglas.setLocation(0, 0);

        // 3. Vaciamos el contenedor y metemos el nuevo panel
        jPanel4.removeAll();
        jPanel4.add(vistaReglas, java.awt.BorderLayout.CENTER);

        // 4. Refrescamos la interfaz para aplicar los cambios
        jPanel4.revalidate();
        jPanel4.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_Reglas_buttonActionPerformed

    private void Penalizar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Penalizar_buttonActionPerformed
        // 1. Creamos la instancia de tu panel de penalizaciones
        adminPenalizar vistaPenalizar = new adminPenalizar();

        // 2. Le asignamos el tamaño exacto del contenedor blanco de abajo
        vistaPenalizar.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaPenalizar.setLocation(0, 0);

        // 3. Vaciamos lo que haya en la zona blanca y metemos el nuevo panel
        jPanel4.removeAll();
        jPanel4.add(vistaPenalizar, java.awt.BorderLayout.CENTER);

        // 4. Le avisamos a Java que redibuje la interfaz para que se vea el cambio
        jPanel4.revalidate();
        jPanel4.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_Penalizar_buttonActionPerformed

    private void AgregarCicla_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCicla_buttonActionPerformed
        // 1. Creamos la instancia del panel para agregar bicicletas
        AdminAgregarcicla vistaAgregarCicla = new AdminAgregarcicla();

        // 2. Le asignamos el tamaño exacto del contenedor (jPanel4)
        vistaAgregarCicla.setSize(jPanel4.getWidth(), jPanel4.getHeight());
        vistaAgregarCicla.setLocation(0, 0);

        // 3. Vaciamos el contenedor y metemos el nuevo panel
        jPanel4.removeAll();
        jPanel4.add(vistaAgregarCicla, java.awt.BorderLayout.CENTER);

        // 4. Refrescamos la interfaz para aplicar los cambios
        jPanel4.revalidate();
        jPanel4.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCicla_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminCiclas_button;
    private javax.swing.JButton AgregarCicla_button;
    private javax.swing.JLabel CERRAR;
    private javax.swing.JButton CerrarSesion_button;
    private javax.swing.JButton Penalizar_button;
    private javax.swing.JButton QuitarEstudiante_button;
    private javax.swing.JButton Reglas_button;
    private javax.swing.JButton Reportes_button;
    private javax.swing.JLabel UNlogo;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panel_superior;
    // End of variables declaration//GEN-END:variables

   
}
