/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;
import com.bicicletas.modelo.Main;
import com.bicicletas.modelo.Student;
import java.awt.Color;

/**
 *
 * @author VALETOR
 */
public class Registro1 extends javax.swing.JPanel {

    /**
     * Creates new form Registro1
     */
public Registro1() {
    initComponents();
    
    this.setFocusable(true);
    javax.swing.SwingUtilities.invokeLater(() -> {
        this.requestFocusInWindow();
    });
    
    setPreferredSize(new java.awt.Dimension(800,460));
    
     //valetor esto es para q no se joda , si quieres cambialo pero cuidado con la transparencia
    enterUser.setOpaque(false);
    enterUser.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    enterID.setOpaque(false);
    enterID.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    enterTIUN.setOpaque(false);
    enterTIUN.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    enterPswrd.setOpaque(false);
    enterPswrd.setBackground(new java.awt.Color(0, 0, 0, 0));
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pswrd_text = new javax.swing.JLabel();
        user_text = new javax.swing.JLabel();
        id_text = new javax.swing.JLabel();
        tiun_text = new javax.swing.JLabel();
        nextPage_button = new javax.swing.JPanel();
        nextPage_text = new javax.swing.JLabel();
        enterUser = new javax.swing.JTextField();
        enterID = new javax.swing.JTextField();
        enterTIUN = new javax.swing.JTextField();
        enterPswrd = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pswrd_text.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        pswrd_text.setText("Contraseña:");
        add(pswrd_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        user_text.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text.setText("Usuario:");
        add(user_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        id_text.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        id_text.setText("Identificación:");
        add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        tiun_text.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        tiun_text.setText("TIUN:");
        add(tiun_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        nextPage_button.setBackground(new java.awt.Color(56, 182, 255));
        nextPage_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextPage_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextPage_text.setBackground(new java.awt.Color(56, 182, 255));
        nextPage_text.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 0, 24)); // NOI18N
        nextPage_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPage_text.setText("Siguiente");
        nextPage_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextPage_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPage_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextPage_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextPage_textMouseExited(evt);
            }
        });
        nextPage_button.add(nextPage_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        add(nextPage_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 300, 60));

        enterUser.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterUser.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterUser.setForeground(new java.awt.Color(0,0,0,50));
        enterUser.setText("Ingrese un usuario");
        enterUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterUserFocusLost(evt);
            }
        });
        enterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterUsermousePressed(evt);
            }
        });
        enterUser.addActionListener(this::enterUserActionPerformed);
        add(enterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 420, -1));

        enterID.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterID.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterID.setForeground(new java.awt.Color(0,0,0,50));
        enterID.setText("Identificación sin puntos");
        enterID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterIDFocusLost(evt);
            }
        });
        enterID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterIDMousePressed(evt);
            }
        });
        add(enterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 420, -1));

        enterTIUN.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterTIUN.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterTIUN.setForeground(new java.awt.Color(0,0,0,50));
        enterTIUN.setText("Ingrese TIUN de su carnet");
        enterTIUN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterTIUNFocusLost(evt);
            }
        });
        enterTIUN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterTIUNMousePressed(evt);
            }
        });
        enterTIUN.addActionListener(this::enterTIUNActionPerformed);
        add(enterTIUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 420, -1));

        enterPswrd.setBackground(new java.awt.Color(56, 182, 255, 9));
        enterPswrd.setFont(new java.awt.Font("Ancizar Serif Medium", 0, 18)); // NOI18N
        enterPswrd.setForeground(new java.awt.Color(0,0,0,50));
        enterPswrd.setText("********");
        enterPswrd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enterPswrdFocusLost(evt);
            }
        });
        enterPswrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enterPswrdMousePressed(evt);
            }
        });
        add(enterPswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 420, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void nextPage_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPage_textMouseClicked
   //ATRIBUTOSS
    Main.tempNombre = enterUser.getText();
    Main.tempCedula = Long.parseLong(enterID.getText());
    Main.tempTiun = Long.parseLong(enterTIUN.getText());
    Main.tempContrasena = new String(enterPswrd.getPassword());
    
    //las dejo para la validación, pero el estudiante se crea con las temporales en registro 2
    long cedula = Long.parseLong(enterID.getText());
    long tiun = Long.parseLong(enterTIUN.getText());
    String password = new String(enterPswrd.getPassword());
    String username = enterUser.getText();
     
    //VAALIDACION PREVIA DE QUE NO SE ENCUENTRE EN LA LISTA DE BLOQUEDOS
    for (Student bloqueado : Main.listaEstudiantesBloqueados) {
        if (bloqueado.getCedula() == cedula && bloqueado.getTiun() == tiun && bloqueado.getUserName().equals(username)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "⚠️ Este estudiante está bloqueado de por vida. No puede registrarse.",
                "Acceso denegado",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return; //CORTA EL FLUJO Y NO DEJA QUE PASE AL REGISTRO 2
        }
    }
    
    
    
    
    //SE ABRE REGISTRO 2
    Registro2 registro2 = new Registro2();
    Signup ventana = (Signup) javax.swing.SwingUtilities.getWindowAncestor(this);

    registro2.setSize(ventana.BLANK.getWidth(), ventana.BLANK.getHeight());
    registro2.setLocation(0,0);

    ventana.BLANK.removeAll();
    ventana.BLANK.add(registro2, java.awt.BorderLayout.CENTER);

    ventana.BLANK.revalidate();
    ventana.BLANK.repaint();
    }//GEN-LAST:event_nextPage_textMouseClicked

    private void nextPage_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPage_textMouseEntered
        nextPage_button.setBackground(new Color(19,134,201));
        nextPage_text.setForeground(Color.WHITE);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 134, 201), 10, true));
    }//GEN-LAST:event_nextPage_textMouseEntered

    private void nextPage_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPage_textMouseExited
        nextPage_button.setBackground(new Color(56,182,255));
        nextPage_text.setForeground(Color.BLACK);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 182, 255), 10, true));
    }//GEN-LAST:event_nextPage_textMouseExited

    private void enterUsermousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterUsermousePressed
    
        if (enterUser.getText().equals("Ingrese un usuario")) {
        enterUser.setText(""); // Deja el cuadro en blanco
        enterUser.setForeground(java.awt.Color.BLACK);
        }
                
    }//GEN-LAST:event_enterUsermousePressed

    private void enterUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterUserFocusLost
    
        if (enterUser.getText().isEmpty()) {
        enterUser.setText("Ingrese un usuario");
        enterUser.setForeground(new java.awt.Color(0, 0, 0, 50));
               
                }    
        
    }//GEN-LAST:event_enterUserFocusLost

    private void enterIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterIDMousePressed
        if (enterID.getText().equals("Identificación sin puntos")) {
        enterID.setText("");
        enterID.setForeground(java.awt.Color.BLACK);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_enterIDMousePressed

    private void enterIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterIDFocusLost
         if (enterID.getText().isEmpty()) {
        enterID.setText("Identificación sin puntos");
        enterID.setForeground(new java.awt.Color(0, 0, 0, 50));
               
                }    


        // TODO add your handling code here:
    }//GEN-LAST:event_enterIDFocusLost

    private void enterTIUNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterTIUNMousePressed
       if (enterTIUN.getText().equals("Ingrese TIUN de su carnet")) {
        enterTIUN.setText("");
        enterTIUN.setForeground(java.awt.Color.BLACK);
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_enterTIUNMousePressed

    private void enterTIUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTIUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTIUNActionPerformed

    private void enterTIUNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterTIUNFocusLost
        // TODO add your handling code here:
        if (enterTIUN.getText().isEmpty()) {
        enterTIUN.setText("Ingrese TIUN de su carnet");
        enterTIUN.setForeground(new java.awt.Color(0, 0, 0, 50));
               
                }  
    }//GEN-LAST:event_enterTIUNFocusLost

    private void enterPswrdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPswrdMousePressed
            // TODO add your handling code here:
            if (enterPswrd.getText().equals("********")) {
        enterPswrd.setText("");
        enterPswrd.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_enterPswrdMousePressed

    private void enterPswrdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterPswrdFocusLost
        // TODO add your handling code here:
        if (enterPswrd.getText().isEmpty()) {
        enterPswrd.setText("********");
        enterPswrd.setForeground(new java.awt.Color(0, 0, 0, 50));
               
                }  
    }//GEN-LAST:event_enterPswrdFocusLost

    private void enterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterID;
    private javax.swing.JPasswordField enterPswrd;
    private javax.swing.JTextField enterTIUN;
    private javax.swing.JTextField enterUser;
    private javax.swing.JLabel id_text;
    private javax.swing.JPanel nextPage_button;
    private javax.swing.JLabel nextPage_text;
    private javax.swing.JLabel pswrd_text;
    private javax.swing.JLabel tiun_text;
    private javax.swing.JLabel user_text;
    // End of variables declaration//GEN-END:variables
}
