/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;

/**
 *
 * @author sammu
 */
public class Reglas extends javax.swing.JPanel {

    /**
     * Creates new form adminPenalizar
     */
    public Reglas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        user_text1 = new javax.swing.JLabel();
        user_text2 = new javax.swing.JLabel();
        user_text3 = new javax.swing.JLabel();
        user_text4 = new javax.swing.JLabel();
        user_text5 = new javax.swing.JLabel();
        user_text6 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 360));

        user_text1.setFont(new java.awt.Font("Ancizar Serif", 1, 36)); // NOI18N
        user_text1.setText("REGLAS");

        user_text2.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text2.setText("Reservas");
        user_text2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_text2MouseClicked(evt);
            }
        });

        user_text3.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text3.setText("Uso");
        user_text3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_text3MouseClicked(evt);
            }
        });

        user_text4.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text4.setText("Penalizaciones");
        user_text4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_text4MouseClicked(evt);
            }
        });
        user_text4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_text4KeyPressed(evt);
            }
        });

        user_text5.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text5.setText("Responsabilidades");
        user_text5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_text5MouseClicked(evt);
            }
        });

        user_text6.setFont(new java.awt.Font("Ancizar Serif", 1, 24)); // NOI18N
        user_text6.setText("Restricciones adicionales");
        user_text6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_text6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(user_text6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addComponent(user_text5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_text4)
                    .addComponent(user_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_text2)
                    .addComponent(user_text3))
                .addGap(479, 479, 479))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(user_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_text2)
                .addGap(18, 18, 18)
                .addComponent(user_text3)
                .addGap(18, 18, 18)
                .addComponent(user_text4)
                .addGap(18, 18, 18)
                .addComponent(user_text5)
                .addGap(18, 18, 18)
                .addComponent(user_text6)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void user_text2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_text2MouseClicked
        user_text2.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        String mensaje = "<html><body style='width: 250px;'>"
                + "• La bicicleta puede reservarse por un máximo de 20 minutos.<br><br>"
                + "• Si en ese tiempo no se retira, la bicicleta vuelve a quedar disponible para otros usuarios.<br><br>"
                + "• Al momento de reservar, el usuario debe indicar la estación de recogida y la estación de entrega."
                + "</body></html>";
                
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Detalles de Reserva", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
});        // TODO add your handling code here:
    }//GEN-LAST:event_user_text2MouseClicked

    private void user_text3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_text3MouseClicked
    user_text3.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        String mensaje = "<html><body style='width: 250px;'>"
                + "• El tiempo máximo de uso es de 15 minutos desde el retiro hasta la devolución.<br><br>"
                + "• La bicicleta debe devolverse en la estación indicada al momento de la reserva.<br><br>"
                + "• Se debe garantizar el buen uso y cuidado de la bicicleta."
                + "</body></html>";
                
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Uso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
});
        // TODO add your handling code here:
    }//GEN-LAST:event_user_text3MouseClicked

    private void user_text4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_text4KeyPressed
 // TODO add your handling code here:
    }//GEN-LAST:event_user_text4KeyPressed

    private void user_text5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_text5MouseClicked
user_text5.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        String mensaje = "<html><body style='width: 250px;'>"
                + "• Verificar el estado de la bicicleta antes de retirarla.<br><br>"
                + "• Reportar cualquier daño o irregularidad inmediatamente.<br><br>"
                + "• Usar la bicicleta únicamente para desplazamientos personales, no para actividades comerciales.<br><br>"
                + "• Respetar las normas de tránsito y seguridad vial."
                + "</body></html>";
                
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Responsabilidades del Usuario", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
});        // TODO add your handling code here:
    }//GEN-LAST:event_user_text5MouseClicked

    private void user_text6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_text6MouseClicked
user_text6.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        String mensaje = "<html><body style='width: 250px;'>"
                + "• No se permite transportar pasajeros.<br><br>"
                + "• No se permite modificar o alterar partes de la bicicleta.<br><br>"
                + "• El préstamo es personal e intransferible: solo el usuario registrado puede usar la bicicleta.<br><br>"
                + "• El incumplimiento reiterado de las reglas puede llevar a la suspensión definitiva del servicio."
                + "</body></html>";
                
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Restricciones Adicionales", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
});        // TODO add your handling code here:
    }//GEN-LAST:event_user_text6MouseClicked

    private void user_text4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_text4MouseClicked
user_text4.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        String mensaje = "<html><body style='width: 250px;'>"
                + "• Mal uso o daños: bloqueo de la cuenta por 15 días.<br><br>"
                + "• No devolución en el tiempo establecido (15 minutos): bloqueo de la cuenta por 15 días.<br><br>"
                + "• En caso de que cuente con 2 penalizaciones, el bloqueo podrá extenderse hasta 30 días o suspensión definitiva."
                + "</body></html>";
                
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Penalizaciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
});               // TODO add your handling code here:
    }//GEN-LAST:event_user_text4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel user_text1;
    private javax.swing.JLabel user_text2;
    private javax.swing.JLabel user_text3;
    private javax.swing.JLabel user_text4;
    private javax.swing.JLabel user_text5;
    private javax.swing.JLabel user_text6;
    // End of variables declaration//GEN-END:variables
}
