/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.bicicletas.views;

import java.time.LocalDate;

/**
 *
 * @author VALETOR
 */
public class Reservar extends javax.swing.JPanel {

    /**
     * Creates new form Reservar
     */
    public Reservar() {
        initComponents();
        setSize(800, 460);
        SetDate();
        
    }
    
    public void SetDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
            "Octubre","Noviembre","Diciembre"};
        fecha_text.setText(dia+"/"+meses[month - 1]+"/"+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha_panel = new javax.swing.JPanel();
        fecha_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha_panel.setBackground(new java.awt.Color(19, 134, 201));

        fecha_text.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 12)); // NOI18N
        fecha_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_text.setText("{dia}/{month}/{year}");

        javax.swing.GroupLayout fecha_panelLayout = new javax.swing.GroupLayout(fecha_panel);
        fecha_panel.setLayout(fecha_panelLayout);
        fecha_panelLayout.setHorizontalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        fecha_panelLayout.setVerticalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(fecha_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 120, 30));
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fecha_panel;
    private javax.swing.JLabel fecha_text;
    // End of variables declaration//GEN-END:variables
}
