
package com.bicicletas.views;

import com.bicicletas.modelo.Main;
import com.bicicletas.modelo.Station;
import com.bicicletas.modelo.Bike;
import com.bicicletas.modelo.DocReader;
import java.awt.Color;
import java.time.LocalDate;

public class Reservar extends javax.swing.JPanel {

    public Reservar() {
        initComponents();
        setSize(800, 460);
        SetDate();
        
    }
    
    public void SetDate(){
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
            "Octubre","Noviembre","Diciembre"};
        fecha_text.setText(dia+"/"+meses[month - 1]+"/"+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha_panel = new javax.swing.JPanel();
        fecha_text = new javax.swing.JLabel();
        estEntrega_select = new javax.swing.JComboBox<>();
        estEntrega_text = new javax.swing.JLabel();
        estRecogida_text = new javax.swing.JLabel();
        estRecogida_select = new javax.swing.JComboBox<>();
        reservar_button = new javax.swing.JPanel();
        reservar_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha_panel.setBackground(new java.awt.Color(19, 134, 201));

        fecha_text.setFont(new java.awt.Font("Ancizar Sans Thin", 0, 12)); // NOI18N
        fecha_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_text.setText("{dia}/{month}/{year}");

        javax.swing.GroupLayout fecha_panelLayout = new javax.swing.GroupLayout(fecha_panel);
        fecha_panel.setLayout(fecha_panelLayout);
        fecha_panelLayout.setHorizontalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        fecha_panelLayout.setVerticalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fecha_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(fecha_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 120, 30));

        estEntrega_select.setFont(new java.awt.Font("Ancizar Serif SemiBold", 0, 18)); // NOI18N
        estEntrega_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Calle 53", "CyT", "Uriel", "Calle 45", "Calle 26", "Calle 30" }));
        add(estEntrega_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 250, 40));

        estEntrega_text.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 36)); // NOI18N
        estEntrega_text.setText("Escoja la estación de entrega");
        add(estEntrega_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        estRecogida_text.setFont(new java.awt.Font("Ancizar Serif SemiBold", 1, 36)); // NOI18N
        estRecogida_text.setText("Escoja la estación de recogida");
        add(estRecogida_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        estRecogida_select.setFont(new java.awt.Font("Ancizar Serif SemiBold", 0, 18)); // NOI18N
        estRecogida_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Calle 53", "CyT", "Uriel", "Calle 45", "Calle 26", "Calle 30" }));
        add(estRecogida_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 250, 40));

        reservar_button.setBackground(new java.awt.Color(56, 182, 255));
        reservar_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reservar_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservar_text.setBackground(new java.awt.Color(56, 182, 255));
        reservar_text.setFont(new java.awt.Font("Ancizar Sans ExtraBold", 0, 24)); // NOI18N
        reservar_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservar_text.setText("Reservar");
        reservar_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reservar_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservar_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservar_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservar_textMouseExited(evt);
            }
        });
        reservar_button.add(reservar_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        add(reservar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 300, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void reservar_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_textMouseClicked
                                        
    String estRec = estRecogida_select.getSelectedItem().toString();
    String estEnt = estEntrega_select.getSelectedItem().toString();

    if (estRec.trim().isEmpty() || estEnt.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione ambas estaciones.");
        return;
    }
    // Buscar estaciones en Main
    com.bicicletas.modelo.Station recogida = null;
    com.bicicletas.modelo.Station entrega = null;

    for (com.bicicletas.modelo.Station s : com.bicicletas.modelo.Main.estaciones) {
        if (s.getName_station().equalsIgnoreCase(estRec)) {
            recogida = s;
        }
        if (s.getName_station().equalsIgnoreCase(estEnt)) {
            entrega = s;
        }
    }

    // Buscar primera bici disponible
    com.bicicletas.modelo.Bike bici = null;

    for (com.bicicletas.modelo.Bike b : recogida.getBicis()) {
        if (b.getState().equals("disponible")) {
            bici = b;
            break;
        }
    }

    if (bici == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay bicicletas disponibles.");
        return;
    }

    // Crear reserva
    com.bicicletas.modelo.Reservar reserva =
            new com.bicicletas.modelo.Reservar(bici, com.bicicletas.modelo.Main.estudianteActual);

    reserva.setEstacionRecogida(recogida);
    reserva.setEstacionEntrega(entrega);

    boolean reservacion = reserva.realizarReserva();

    if (reservacion) {
        com.bicicletas.modelo.Main.estudianteActual.setReserva(reserva);
        DocReader.guardarReserva(reserva);
        javax.swing.JOptionPane.showMessageDialog(this,"Reserva creada con éxito. / ID de la bicicleta: " + bici.getId());
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,"No se pudo crear la reserva.");
    }


    }//GEN-LAST:event_reservar_textMouseClicked

    private void reservar_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_textMouseEntered
        reservar_button.setBackground(new Color(19,134,201));
        reservar_text.setForeground(Color.WHITE);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 134, 201), 10, true));
    }//GEN-LAST:event_reservar_textMouseEntered

    private void reservar_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservar_textMouseExited
        reservar_button.setBackground(new Color(56,182,255));
        reservar_text.setForeground(Color.BLACK);
        //iniciarSesion_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 182, 255), 10, true));
    }//GEN-LAST:event_reservar_textMouseExited
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estEntrega_select;
    private javax.swing.JLabel estEntrega_text;
    private javax.swing.JComboBox<String> estRecogida_select;
    private javax.swing.JLabel estRecogida_text;
    private javax.swing.JPanel fecha_panel;
    private javax.swing.JLabel fecha_text;
    private javax.swing.JPanel reservar_button;
    private javax.swing.JLabel reservar_text;
    // End of variables declaration//GEN-END:variables
}
